
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 13 11:12:22 EST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int RBRACK = 11;
  public static final int GEQ = 23;
  public static final int AND = 20;
  public static final int IS = 27;
  public static final int ELSE = 17;
  public static final int PLUS = 3;
  public static final int INT = 30;
  public static final int OR = 21;
  public static final int RPAREN = 8;
  public static final int THEN = 19;
  public static final int SEMI = 2;
  public static final int WHILE = 15;
  public static final int NOT = 22;
  public static final int LBRACK = 10;
  public static final int GRAT = 32;
  public static final int FUNCTION = 12;
  public static final int IF = 18;
  public static final int LPAREN = 9;
  public static final int ID = 33;
  public static final int DO = 16;
  public static final int BOOLEAN = 28;
  public static final int STRING = 29;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int NUMBER = 13;
  public static final int DIVIDE = 6;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 26;
  public static final int LEQ = 24;
  public static final int NEQ = 25;
  public static final int LESS = 31;
  public static final int UMINUS = 7;
}

